server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: COURSE-SERVICE
          uri: lb://COURSE-SERVICE
          predicates:
            - Path = /courses/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
