server:
  port: 8080
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      globalcors:
        cors-configuration:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              -GET
              -POST
              -PUT
              -DELETE
              -OPTIONS
            allowedHeaders: "*"
#            allowCredentials: true
      routes:
        - id: COURSE-SERVICE
          uri: lb://COURSE-SERVICE
          predicates:
            - Path=/courses/**
          filters:
            - AuthenticationFilter

        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
