#spring.application.name=api-gateway
#server.port = 8080
#eureka.client.register-with-eureka = false
#eureka.client.fetch-registry = false
#spring.cloud.config.import-check.enabled = false;

server:
  port: 8081

spring:
  application:
    name: AUTH-SERVICE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    hostname: localhost